services:
    be-service:
        build:
            context: ./url-shortener-go
            dockerfile: Dockerfile.local
        ports:
            - '8002:8002'
        volumes:
            - "./url-shortener-go:/url-shortener-go"