services:
    be-service:
        build:
            context: ./
            dockerfile: Dockerfile.production
        ports:
            - '8002:8002'
        restart: always
        networks:
           - "url-shortener"
networks:
    url-shortener:
       driver: bridge