FROM golang:1.20-alpine3.19 as builder

WORKDIR /app
COPY . /app
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/executable.sh

FROM alpine:3.19.1

WORKDIR /app
COPY --from=builder /app/executable.sh /app/executable.sh
CMD ["/app/executable.sh"]