services:
    be-service:
        container_name: url-shortener-be-service
        image: nicodwik/url-shortener-go:1.0
        ports:
            - '${APP_PORT:-8001}:8001'
        restart: always
        environment:
            - APP_PORT=8001
            - DB_HOST=
            - DB_PORT=
            - DB_PASSWORD=
            - REDIS_HOST=
            - REDIS_PORT=
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
           - "url-shortener-network"
networks:
    url-shortener-network:
        name: url-shortener-network
        driver: bridge