FROM golang:1.20

ENV DB_HOST "host.docker.internal"
ENV DB_PORT "3306"

ENV REDIS_HOST "host.docker.internal"
ENV REDIS_PORT "6379"

WORKDIR /app

COPY . /app

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/executable.sh

CMD ["./executable.sh"]

EXPOSE 8000