services:
    be-service:
        build:
            context: ./url-shortener-go
            dockerfile: Dockerfile.local
        ports:
            - '${APP_PORT:-8001}:8001'
        volumes:
            - "./url-shortener-go:/url-shortener-go"