services:
    be-service:
        build:
            context: ./
            dockerfile: Dockerfile.production
        ports:
            - '8002:8002'
        restart: always
        networks:
           - "url-shortener-network"
networks:
    url-shortener-network:
        name: url-shortener-network
        driver: bridge