FROM golang:1.20-alpine3.19 as builder

WORKDIR /app
COPY . /app
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/executable.sh

FROM alpine/curl:8.5.0

WORKDIR /app
COPY .env .
COPY --from=builder /app/executable.sh /app/executable.sh
CMD ["/app/executable.sh"]