services:
    be-service:
        container_name: url-shortener-be-service
        build:
            context: ./
            dockerfile: Dockerfile.production
        ports:
            - '${APP_PORT:-8001}:8001'
        restart: always
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
           - "url-shortener-network"
networks:
    url-shortener-network:
        name: url-shortener-network
        driver: bridge