name: Auto Deployment 🚀

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23' 

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        file: ./Dockerfile.production
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener-go:latest

    - name: Trigger Portainer webhook
      run: curl -X POST https://portainer.nico-dk.my.id/api/webhooks/${{ secrets.PORTAINER_WEBHOOK_ID }}